-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 13:27:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCat` INT NOT NULL,
  `nameCat` VARCHAR(45) NULL,
  PRIMARY KEY (`idCat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `nameProduct` VARCHAR(45) NULL,
  `Categorie_idCat` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Categorie_idx` (`Categorie_idCat` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Categorie`
    FOREIGN KEY (`Categorie_idCat`)
    REFERENCES `mydb`.`Categorie` (`idCat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
